### ISSUE TITLE
同学您好，我在build_file_list这一步出错

### ISSUE THREAD

**Issue by sucaohan** [milkcat0904/temporal-segment-network-pytorch#2]
我提取的是hmdb51的特征，并且像原文件夹存放视频一样，存放光流和视频桢特征，但是运行的时候出现错误。
ubuntu-507@HP-Z620:~/temporal-segment-networks$ bash scripts/build_file_list.sh hmdb51 /home/ubuntu-507/Downloads/LYY/datasets/hmdb51_feature
processing dataset hmdb51
parse frames under folder /home/ubuntu-507/Downloads/LYY/datasets/hmdb51_feature
0 videos parsed
frame folder analysis done
writing list files for training/testing
Traceback (most recent call last):
  File "tools/build_file_list.py", line 40, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/ubuntu-507/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 59, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/ubuntu-507/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 49, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: '20060723sfjffsomelikeitwarmed_eat_u_cm_np1_fr_med_2'
请问您知道该怎么解决么，期待回信，万分感谢

**Comment by yangyuke001** [comment]
@sucaohan 
你好，我也在类似的地方出问题了，请问一下：
你的hmdb51的文件组织形式是什么样的呢？
包括视频/光流/图片/文件list等
多谢！
